;------------------------------------------------------------------------------;
;                                                                              ;
;          This directory contains target functionality under debug.           ;
;    This file contains globally used variables without pre-defined values.    ;
;                                                                              ;
;------------------------------------------------------------------------------;

; Reserved.